version: "3.9"

services:
  # minio:
  #   container_name: minio
  #   image: minio/minio:RELEASE.2022-10-08T20-11-00Z
  #   ports:
  #     - "9000:9000"
  #     - "9001:9001"
  #   environment:
  #     - MINIO_ROOT_USER=${MINIO_ROOT_USER}
  #     - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
  #   entrypoint: sh
  #   command: -c "/opt/bin/minio server /export --address :9000 --console-address :9001"
  #   volumes:
  #     - ./docker/external-service/minio/data:/export

  # postgres:
  #   container_name: postgres
  #   image: postgres:15
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - ./docker/external-service/postgres/init:/docker-entrypoint-initdb.d
  #     - ./docker/external-service/postgres/data:/var/lib/postgresql/data
  #   environment:
  #     POSTGRES_USER: ${POSTGRES_USER}
  #     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  server:
    container_name: server
    build:
      context: .
      dockerfile: ./docker/server/Dockerfile
    stdin_open: true
    ports:
      - 8000:8000


